{% set name = "XStatic-Bootstrap" %}
{% set version = "4.5.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf67d205437b32508a88b69a7e7c5bbe2ca5a8ae71097391a6a6f510ebfd2820

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - xstatic.pkg.bootstrap

about:
  home: https://xstatic.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Twitter Bootstrap packaged for setuptools

  description: |
    Quickly design and customize responsive mobile-first sites with Bootstrap, |
    the world’s most popular front-end open source toolkit, featuring Sass variables and mixins,|
    responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.
  doc_url: https://xstatic.readthedocs.io/
  dev_url: https://github.com/xstatic-py/xstatic-bootstrap

extra:
  recipe-maintainers:
    - ReimarBauer
